eureka:
  instance:
    prefer-ip-address: true
    #表示 eureka server 在接收到上一个心跳之后等待下一个心跳的秒数（默认 90 秒），若不能在指定时间内收到心跳，则移除此实例，并禁止此实例的流量
    lease-expiration-duration-in-seconds: 20
    # 表示eureka client发送心跳给server端的频率（默认30秒）
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka-service/eureka/

spring:
  # PROFILES
  profiles:
    active: local
  # IDENTITY
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - OAuth2= true
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        - id: customOne
          uri: lb://client-demo
          predicates:
            - Path=/customOne/api/**
          filters:
            - Custom= true
            - StripPrefix= 2
        - id: customTwo
          uri: lb://clientTwo
          predicates:
            - Path=/customTwo/api/**
          filters:
            - StripPrefix= 2
  # AOP
  aop:
    auto: true
    proxy-target-class: false
  # FILE ENCODING (FileEncodingApplicationListener)
  mandatory-file-encoding: utf-8
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true
  # JACKSON (JacksonProperties)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss



server:
  port: 8080
  servlet:
    context-path: /


